# Generated by Django 2.2.19 on 2022-09-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220801_2331'),
        ('posts', '0007_auto_20220910_2233'),
    ]

    operations = [
    ]
